-- HobbyMate 관리자 임시 본인인증 컬럼 및 이력 확장
-- 대상: v0.1 회원 테이블과 v0.2 관리자 이력 테이블이 이미 생성된 기존 DB
-- DBMS: MariaDB
-- 적용 전 운영 백업 및 스키마 버전 확인 필수

ALTER TABLE HM_MEMBER
    ADD COLUMN IDENTITY_VERIFICATION_METHOD VARCHAR(30) NULL
        COMMENT '본인인증 방식: ADMIN_TEMP 임시 관리자 인증, 실제 인증기관 코드'
        AFTER IDENTITY_VERIFIED_YN,
    ADD COLUMN IDENTITY_VERIFIED_BY BIGINT UNSIGNED NULL
        COMMENT '본인인증 처리 관리자 회원 FK(ADMIN_TEMP인 경우)'
        AFTER IDENTITY_VERIFIED_AT,
    ADD COLUMN IDENTITY_VERIFICATION_REASON VARCHAR(2000) NULL
        COMMENT '관리자 임시 본인인증 처리 사유'
        AFTER IDENTITY_VERIFIED_BY,
    ADD COLUMN UPDATED_BY BIGINT UNSIGNED NULL
        COMMENT '최종 수정 관리자 회원 FK'
        AFTER UPDATED_AT,
    ADD KEY IX_HM_MEMBER_IDENTITY_VERIFICATION
        (IDENTITY_VERIFIED_YN, IDENTITY_VERIFICATION_METHOD),
    ADD KEY IX_HM_MEMBER_IDENTITY_VERIFIED_BY (IDENTITY_VERIFIED_BY),
    ADD KEY IX_HM_MEMBER_UPDATED_BY (UPDATED_BY),
    ADD CONSTRAINT FK_HM_MEMBER_IDENTITY_VERIFIED_BY
        FOREIGN KEY (IDENTITY_VERIFIED_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    ADD CONSTRAINT FK_HM_MEMBER_UPDATED_BY
        FOREIGN KEY (UPDATED_BY) REFERENCES HM_MEMBER (MEMBER_ID);

ALTER TABLE HM_ADMIN_ACTION_HISTORY
    DROP CONSTRAINT CK_HM_ADMIN_ACTION_HISTORY_ACTION_TYPE,
    ADD COLUMN BEFORE_VERIFICATION_METHOD VARCHAR(30) NULL
        COMMENT '처리 전 본인인증 방식'
        AFTER RESULT_MESSAGE,
    ADD COLUMN AFTER_VERIFICATION_METHOD VARCHAR(30) NULL
        COMMENT '처리 후 본인인증 방식'
        AFTER BEFORE_VERIFICATION_METHOD,
    ADD COLUMN BEFORE_CI_HASH VARCHAR(255) NULL
        COMMENT '처리 전 CI 해시(관리자 화면 및 로그 노출 금지)'
        AFTER AFTER_VERIFICATION_METHOD,
    ADD COLUMN AFTER_CI_HASH VARCHAR(255) NULL
        COMMENT '처리 후 CI 해시(관리자 화면 및 로그 노출 금지)'
        AFTER BEFORE_CI_HASH,
    ADD COLUMN PROCESSING_TYPE VARCHAR(20) NULL
        COMMENT '처리 단위: INDIVIDUAL 개별, BATCH 일괄'
        AFTER AFTER_CI_HASH,
    ADD COLUMN OPERATION_ID VARCHAR(36) NULL
        COMMENT '동일 일괄 요청 식별 UUID'
        AFTER PROCESSING_TYPE,
    ADD KEY IX_HM_ADMIN_ACTION_HISTORY_OPERATION (OPERATION_ID),
    ADD CONSTRAINT CK_HM_ADMIN_ACTION_HISTORY_ACTION_TYPE
        CHECK (
            ACTION_TYPE IN (
                'SUSPEND',
                'UNSUSPEND',
                'BLOCK',
                'UNBLOCK',
                'DELETE',
                'RESTORE',
                'APPROVE',
                'REJECT',
                'COMPLETE',
                'UPDATE',
                'ADMIN_TEMP_AUTH',
                'ADMIN_TEMP_AUTH_CANCEL',
                'ADMIN_TEMP_AUTH_UPDATE'
            )
        ),
    ADD CONSTRAINT CK_HM_ADMIN_ACTION_HISTORY_PROCESSING_TYPE
        CHECK (
            PROCESSING_TYPE IS NULL
            OR PROCESSING_TYPE IN ('INDIVIDUAL', 'BATCH')
        );
