-- HobbyMate 서비스 정책 확장 v0.4
-- 대상: v0.1~v0.3이 적용된 기존 MariaDB
-- 목적: 모임·만남·게시판·알림·신고·관리자·개인정보 확정 정책 반영
-- 주의: 운영 데이터가 존재하므로 DROP TABLE 및 데이터 초기화를 수행하지 않는다.

SET NAMES utf8mb4;

-- 1. 회원 권한·상태·탈퇴 후 개인정보 정리 구조
ALTER TABLE HM_MEMBER
    DROP CONSTRAINT CK_HM_MEMBER_ROLE,
    DROP CONSTRAINT CK_HM_MEMBER_STATUS,
    MODIFY NAME VARCHAR(50) NULL COMMENT '본인인증 이름, 탈퇴 30일 후 익명화 가능',
    MODIFY PHONE VARCHAR(30) NULL COMMENT '휴대폰 번호, 탈퇴 30일 후 익명화 가능',
    MODIFY BIRTH_DATE DATE NULL COMMENT '생년월일, 탈퇴 30일 후 익명화 가능',
    MODIFY GENDER VARCHAR(10) NULL COMMENT '성별, 탈퇴 30일 후 익명화 가능',
    ADD COLUMN PROFILE_THUMBNAIL_URL VARCHAR(1000) NULL COMMENT '200x200 프로필 썸네일 저장 키' AFTER PROFILE_IMAGE_URL,
    ADD COLUMN PERSONAL_INFO_PURGED_AT DATETIME NULL COMMENT '탈퇴 후 개인정보 삭제·익명화 일시' AFTER WITHDRAWN_AT,
    ADD KEY IX_HM_MEMBER_STATUS_CREATED (MEMBER_STATUS, CREATED_AT),
    ADD CONSTRAINT CK_HM_MEMBER_ROLE CHECK (MEMBER_ROLE IN ('USER','ADMIN','SUPER_ADMIN')),
    ADD CONSTRAINT CK_HM_MEMBER_STATUS CHECK (MEMBER_STATUS IN ('ACTIVE','SUSPENDED','PERMANENT_BANNED','WITHDRAWN')),
    ADD CONSTRAINT CK_HM_MEMBER_GENDER_V04 CHECK (GENDER IS NULL OR GENDER IN ('FEMALE','MALE'));

-- 기존 성별 CHECK는 NOT NULL 전제를 제거하기 위해 교체한다.
ALTER TABLE HM_MEMBER DROP CONSTRAINT CK_HM_MEMBER_GENDER;

-- 2. 모임 폐쇄 구분·복구·최근 활동
ALTER TABLE HM_CLUB
    ADD COLUMN JOIN_GUIDE VARCHAR(1000) NULL COMMENT '승인제 가입 신청 안내·질문, 화면 입력 최대 500자' AFTER JOIN_TYPE,
    ADD COLUMN CLOSED_TYPE VARCHAR(20) NULL COMMENT '폐쇄 유형: LEADER 자진폐쇄, ADMIN 관리자폐쇄' AFTER RECRUIT_STATUS,
    ADD COLUMN CLOSED_BY BIGINT UNSIGNED NULL COMMENT '폐쇄 처리 회원 FK' AFTER CLOSED_TYPE,
    ADD COLUMN CLOSED_REASON VARCHAR(2000) NULL COMMENT '폐쇄 사유' AFTER CLOSED_BY,
    ADD COLUMN RECOVERABLE_UNTIL DATETIME NULL COMMENT '복구 가능 기한' AFTER CLOSED_AT,
    ADD COLUMN LAST_ACTIVITY_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최근 활동 일시' AFTER UPDATED_AT,
    ADD KEY IX_HM_CLUB_RECENT_ACTIVITY (CLUB_STATUS, LAST_ACTIVITY_AT),
    ADD KEY IX_HM_CLUB_CREATED (CREATED_AT),
    ADD KEY IX_HM_CLUB_CLOSED_BY (CLOSED_BY),
    ADD CONSTRAINT FK_HM_CLUB_CLOSED_BY FOREIGN KEY (CLOSED_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    ADD CONSTRAINT CK_HM_CLUB_CLOSED_TYPE CHECK (CLOSED_TYPE IS NULL OR CLOSED_TYPE IN ('LEADER','ADMIN'));

-- 3. 모임 회원 상태와 승인 대기 중복 방지
ALTER TABLE HM_CLUB_MEMBER
    DROP CONSTRAINT CK_HM_CLUB_MEMBER_STATUS;

UPDATE HM_CLUB_MEMBER
SET MEMBER_STATUS = 'LEFT'
WHERE MEMBER_STATUS = 'WITHDRAWN';

ALTER TABLE HM_CLUB_MEMBER
    ADD CONSTRAINT CK_HM_CLUB_MEMBER_STATUS CHECK (MEMBER_STATUS IN ('ACTIVE','LEFT','KICKED'));

ALTER TABLE HM_CLUB_JOIN_REQUEST
    ADD COLUMN WAITING_MEMBER_ID BIGINT UNSIGNED
        AS (CASE WHEN REQUEST_STATUS = 'WAITING' THEN MEMBER_ID ELSE NULL END) PERSISTENT
        COMMENT '승인 대기 중복 방지용 생성 컬럼',
    ADD UNIQUE KEY UK_HM_CLUB_JOIN_WAITING (CLUB_ID, WAITING_MEMBER_ID);

-- 4. 만남 선착순·대기 제안·취소·출석/노쇼
ALTER TABLE HM_MEETING
    DROP CONSTRAINT CK_HM_MEETING_MAX_MEMBER_COUNT,
    ADD COLUMN PARTICIPATION_METHOD VARCHAR(20) NOT NULL DEFAULT 'FIRST_COME' COMMENT '참가 방식: FIRST_COME 선착순' AFTER MEETING_TYPE,
    ADD COLUMN CANCELED_BY BIGINT UNSIGNED NULL COMMENT '취소 처리 회원 FK' AFTER CANCELED_AT,
    ADD COLUMN CANCEL_TYPE VARCHAR(20) NULL COMMENT '취소 주체: CREATOR, LEADER, MANAGER, ADMIN, CLUB_CLOSED' AFTER CANCELED_BY,
    ADD COLUMN CANCEL_REASON VARCHAR(2000) NULL COMMENT '취소 사유' AFTER CANCEL_TYPE,
    ADD KEY IX_HM_MEETING_CANCELED_BY (CANCELED_BY),
    ADD KEY IX_HM_MEETING_CREATED (CREATED_AT),
    ADD CONSTRAINT FK_HM_MEETING_CANCELED_BY FOREIGN KEY (CANCELED_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    ADD CONSTRAINT CK_HM_MEETING_PARTICIPATION_METHOD CHECK (PARTICIPATION_METHOD = 'FIRST_COME'),
    ADD CONSTRAINT CK_HM_MEETING_CANCEL_TYPE CHECK (CANCEL_TYPE IS NULL OR CANCEL_TYPE IN ('CREATOR','LEADER','MANAGER','ADMIN','CLUB_CLOSED')),
    ADD CONSTRAINT CK_HM_MEETING_MAX_MEMBER_COUNT CHECK (MAX_MEMBER_COUNT >= 2);

UPDATE HM_MEETING_PARTICIPANT
SET PARTICIPATION_STATUS = 'CONFIRMED',
    CONFIRMED_AT = COALESCE(CONFIRMED_AT, APPLIED_AT)
WHERE PARTICIPATION_STATUS = 'APPLIED';

ALTER TABLE HM_MEETING_PARTICIPANT
    DROP CONSTRAINT CK_HM_MEETING_PARTICIPANT_STATUS,
    ADD COLUMN WAITING_ORDER INT UNSIGNED NULL COMMENT '대기 순번' AFTER PARTICIPATION_STATUS,
    ADD COLUMN WAITING_REGISTERED_AT DATETIME NULL COMMENT '대기 등록 일시' AFTER WAITING_ORDER,
    ADD COLUMN OFFERED_AT DATETIME NULL COMMENT '참가 제안 일시' AFTER WAITING_REGISTERED_AT,
    ADD COLUMN OFFER_EXPIRES_AT DATETIME NULL COMMENT '참가 제안 만료 일시' AFTER OFFERED_AT,
    ADD COLUMN OFFER_RESPONDED_AT DATETIME NULL COMMENT '참가 제안 응답 일시' AFTER OFFER_EXPIRES_AT,
    ADD COLUMN OFFER_RESPONSE VARCHAR(20) NULL COMMENT '제안 응답: ACCEPTED, DECLINED, EXPIRED' AFTER OFFER_RESPONDED_AT,
    ADD COLUMN ATTENDED_YN CHAR(1) NULL COMMENT '실제 참석 여부' AFTER ATTENDANCE_PROCESSED_AT,
    ADD COLUMN NO_SHOW_YN CHAR(1) NULL COMMENT '노쇼 여부' AFTER ATTENDED_YN,
    ADD UNIQUE KEY UK_HM_MEETING_WAITING_ORDER (MEETING_ID, WAITING_ORDER),
    ADD CONSTRAINT CK_HM_MEETING_PARTICIPANT_STATUS CHECK (PARTICIPATION_STATUS IN ('CONFIRMED','WAITING','OFFERED','CANCELED','ATTENDED','ABSENT')),
    ADD CONSTRAINT CK_HM_MEETING_OFFER_RESPONSE CHECK (OFFER_RESPONSE IS NULL OR OFFER_RESPONSE IN ('ACCEPTED','DECLINED','EXPIRED')),
    ADD CONSTRAINT CK_HM_MEETING_ATTENDED_YN CHECK (ATTENDED_YN IS NULL OR ATTENDED_YN IN ('Y','N')),
    ADD CONSTRAINT CK_HM_MEETING_NO_SHOW_YN CHECK (NO_SHOW_YN IS NULL OR NO_SHOW_YN IN ('Y','N'));

-- 5. 모임 게시판 유형·연결 제약·댓글 1단계
ALTER TABLE HM_CLUB_POST
    DROP CONSTRAINT CK_HM_CLUB_POST_TYPE,
    DROP CONSTRAINT CK_HM_CLUB_POST_STATUS;

UPDATE HM_CLUB_POST SET POST_TYPE = 'MEETING' WHERE POST_TYPE = 'MEETING_RECRUIT';
UPDATE HM_CLUB_POST SET POST_TYPE = 'REVIEW' WHERE POST_TYPE = 'MEETING_REVIEW';

ALTER TABLE HM_CLUB_POST
    ADD COLUMN MEETING_RECRUIT_KEY BIGINT UNSIGNED
        AS (CASE WHEN POST_TYPE = 'MEETING' THEN MEETING_ID ELSE NULL END) PERSISTENT
        COMMENT '만남별 모집글 중복 방지용 생성 컬럼',
    ADD COLUMN REVIEW_AUTHOR_KEY BIGINT UNSIGNED
        AS (CASE WHEN POST_TYPE = 'REVIEW' THEN AUTHOR_MEMBER_ID ELSE NULL END) PERSISTENT
        COMMENT '만남별 회원 후기 중복 방지용 생성 컬럼',
    ADD UNIQUE KEY UK_HM_CLUB_POST_MEETING (MEETING_RECRUIT_KEY),
    ADD UNIQUE KEY UK_HM_CLUB_POST_REVIEW (MEETING_ID, REVIEW_AUTHOR_KEY),
    ADD KEY IX_HM_CLUB_POST_CREATED (CREATED_AT),
    ADD FULLTEXT KEY FX_HM_CLUB_POST_SEARCH (TITLE, CONTENT),
    ADD CONSTRAINT CK_HM_CLUB_POST_TYPE CHECK (POST_TYPE IN ('NOTICE','FREE','MEETING','REVIEW')),
    ADD CONSTRAINT CK_HM_CLUB_POST_STATUS CHECK (POST_STATUS IN ('ACTIVE','CANCELED','DELETED','BLOCKED'));

ALTER TABLE HM_CLUB_COMMENT
    ADD COLUMN DEPTH TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '댓글 깊이: 0 댓글, 1 답글' AFTER PARENT_COMMENT_ID,
    ADD CONSTRAINT CK_HM_CLUB_COMMENT_DEPTH CHECK (DEPTH IN (0,1));

ALTER TABLE HM_BOARD_COMMENT
    ADD COLUMN DEPTH TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '댓글 깊이: 0 댓글, 1 답글' AFTER PARENT_COMMENT_ID,
    ADD CONSTRAINT CK_HM_BOARD_COMMENT_DEPTH CHECK (DEPTH IN (0,1));

ALTER TABLE HM_BOARD_POST
    ADD FULLTEXT KEY FX_HM_BOARD_POST_SEARCH (TITLE, CONTENT);

ALTER TABLE HM_CLUB
    ADD FULLTEXT KEY FX_HM_CLUB_SEARCH (CLUB_NAME, CLUB_SUMMARY, CLUB_DESCRIPTION);

ALTER TABLE HM_MEETING
    ADD FULLTEXT KEY FX_HM_MEETING_TITLE (MEETING_TITLE);

-- 6. 스토리지 전환을 위한 이미지 메타데이터
ALTER TABLE HM_CLUB_POST_IMAGE
    ADD COLUMN STORAGE_PROVIDER VARCHAR(20) NOT NULL DEFAULT 'LOCAL' COMMENT '저장소: LOCAL, S3' AFTER STORED_FILE_NAME,
    ADD COLUMN STORAGE_KEY VARCHAR(1000) NULL COMMENT '외부 노출하지 않는 저장 키' AFTER STORAGE_PROVIDER,
    ADD CONSTRAINT CK_HM_CLUB_POST_IMAGE_STORAGE CHECK (STORAGE_PROVIDER IN ('LOCAL','S3'));

ALTER TABLE HM_BOARD_POST_IMAGE
    ADD COLUMN STORAGE_PROVIDER VARCHAR(20) NOT NULL DEFAULT 'LOCAL' COMMENT '저장소: LOCAL, S3' AFTER STORED_FILE_NAME,
    ADD COLUMN STORAGE_KEY VARCHAR(1000) NULL COMMENT '외부 노출하지 않는 저장 키' AFTER STORAGE_PROVIDER,
    ADD CONSTRAINT CK_HM_BOARD_POST_IMAGE_STORAGE CHECK (STORAGE_PROVIDER IN ('LOCAL','S3'));

-- 7. 신고 정책
ALTER TABLE HM_REPORT
    DROP CONSTRAINT CK_HM_REPORT_REASON,
    DROP CONSTRAINT CK_HM_REPORT_STATUS;

UPDATE HM_REPORT SET REPORT_REASON = 'SPAM_AD' WHERE REPORT_REASON = 'SPAM';
UPDATE HM_REPORT SET REPORT_REASON = 'ABUSE_DEFAMATION' WHERE REPORT_REASON = 'ABUSE';
UPDATE HM_REPORT SET REPORT_REASON = 'SEXUAL_CONTENT' WHERE REPORT_REASON = 'INAPPROPRIATE';
UPDATE HM_REPORT SET REPORT_REASON = 'FRAUD_FALSE_INFORMATION' WHERE REPORT_REASON = 'FRAUD';
UPDATE HM_REPORT SET REPORT_REASON = 'OTHER' WHERE REPORT_REASON = 'PRIVACY';
UPDATE HM_REPORT SET REPORT_STATUS = 'COMPLETED' WHERE REPORT_STATUS = 'RESOLVED';

ALTER TABLE HM_REPORT
    MODIFY REPORT_CONTENT VARCHAR(500) NULL COMMENT '신고 상세 사유, OTHER일 때 필수(최대 500자)',
    ADD COLUMN FALSE_REPORT_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '허위·악의적 신고 판정 여부' AFTER PROCESS_RESULT,
    ADD COLUMN ADMIN_MEMO VARCHAR(2000) NULL COMMENT '관리자 내부 메모' AFTER FALSE_REPORT_YN,
    ADD UNIQUE KEY UK_HM_REPORT_DUPLICATE (REPORTER_MEMBER_ID, TARGET_TYPE, TARGET_ID),
    ADD CONSTRAINT CK_HM_REPORT_REASON CHECK (REPORT_REASON IN ('SPAM_AD','ABUSE_DEFAMATION','SEXUAL_CONTENT','HATE_DISCRIMINATION','FRAUD_FALSE_INFORMATION','ILLEGAL_ACTIVITY','CLUB_RULE_VIOLATION','OTHER')),
    ADD CONSTRAINT CK_HM_REPORT_STATUS CHECK (REPORT_STATUS IN ('RECEIVED','REVIEWING','COMPLETED','REJECTED')),
    ADD CONSTRAINT CK_HM_REPORT_FALSE_YN CHECK (FALSE_REPORT_YN IN ('Y','N'));

-- 8. 모임 회원 이력·영구 가입 제한·즐겨찾기
CREATE TABLE IF NOT EXISTS HM_CLUB_MEMBER_HISTORY (
    CLUB_MEMBER_HISTORY_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '모임 회원 이력 PK',
    CLUB_ID BIGINT UNSIGNED NOT NULL COMMENT '모임 FK',
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '대상 회원 FK',
    EVENT_TYPE VARCHAR(30) NOT NULL COMMENT 'JOIN, LEFT, KICKED, ROLE_CHANGED, LEADER_TRANSFER, CLUB_CLOSED',
    BEFORE_ROLE VARCHAR(20) NULL COMMENT '변경 전 역할',
    AFTER_ROLE VARCHAR(20) NULL COMMENT '변경 후 역할',
    BEFORE_STATUS VARCHAR(20) NULL COMMENT '변경 전 상태',
    AFTER_STATUS VARCHAR(20) NULL COMMENT '변경 후 상태',
    EVENT_REASON VARCHAR(2000) NULL COMMENT '처리 사유',
    ACTION_BY BIGINT UNSIGNED NULL COMMENT '처리 회원 FK',
    REJOIN_AVAILABLE_AT DATETIME NULL COMMENT '12시간 재가입 제한 종료 일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '처리 일시',
    PRIMARY KEY (CLUB_MEMBER_HISTORY_ID),
    KEY IX_HM_CLUB_MEMBER_HISTORY_MEMBER (CLUB_ID, MEMBER_ID, CREATED_AT),
    KEY IX_HM_CLUB_MEMBER_HISTORY_ACTION_BY (ACTION_BY),
    CONSTRAINT FK_HM_CLUB_MEMBER_HISTORY_CLUB FOREIGN KEY (CLUB_ID) REFERENCES HM_CLUB (CLUB_ID),
    CONSTRAINT FK_HM_CLUB_MEMBER_HISTORY_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_CLUB_MEMBER_HISTORY_ACTION FOREIGN KEY (ACTION_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT CK_HM_CLUB_MEMBER_HISTORY_EVENT CHECK (EVENT_TYPE IN ('JOIN','LEFT','KICKED','ROLE_CHANGED','LEADER_TRANSFER','CLUB_CLOSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='모임 가입·탈퇴·강퇴·역할 변경 이력';

CREATE TABLE IF NOT EXISTS HM_CLUB_BAN (
    CLUB_BAN_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '모임 영구 가입 제한 PK',
    CLUB_ID BIGINT UNSIGNED NOT NULL COMMENT '모임 FK',
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '제한 회원 FK',
    BANNED_BY BIGINT UNSIGNED NOT NULL COMMENT '제한 처리 회원 FK',
    BAN_REASON VARCHAR(2000) NULL COMMENT '강퇴·제한 사유',
    ACTIVE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '제한 활성 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
    RELEASED_AT DATETIME NULL COMMENT '해제 일시',
    RELEASED_BY BIGINT UNSIGNED NULL COMMENT '해제 처리 회원 FK',
    PRIMARY KEY (CLUB_BAN_ID),
    UNIQUE KEY UK_HM_CLUB_BAN_CLUB_MEMBER (CLUB_ID, MEMBER_ID),
    KEY IX_HM_CLUB_BAN_MEMBER (MEMBER_ID, ACTIVE_YN),
    CONSTRAINT FK_HM_CLUB_BAN_CLUB FOREIGN KEY (CLUB_ID) REFERENCES HM_CLUB (CLUB_ID),
    CONSTRAINT FK_HM_CLUB_BAN_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_CLUB_BAN_BANNED_BY FOREIGN KEY (BANNED_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_CLUB_BAN_RELEASED_BY FOREIGN KEY (RELEASED_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT CK_HM_CLUB_BAN_ACTIVE_YN CHECK (ACTIVE_YN IN ('Y','N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='모임 영구 가입 제한';

CREATE TABLE IF NOT EXISTS HM_CLUB_FAVORITE (
    CLUB_FAVORITE_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '모임 즐겨찾기 PK',
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '회원 FK',
    CLUB_ID BIGINT UNSIGNED NOT NULL COMMENT '모임 FK',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
    PRIMARY KEY (CLUB_FAVORITE_ID),
    UNIQUE KEY UK_HM_CLUB_FAVORITE_MEMBER_CLUB (MEMBER_ID, CLUB_ID),
    KEY IX_HM_CLUB_FAVORITE_CLUB (CLUB_ID),
    CONSTRAINT FK_HM_CLUB_FAVORITE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_CLUB_FAVORITE_CLUB FOREIGN KEY (CLUB_ID) REFERENCES HM_CLUB (CLUB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공개 모임 즐겨찾기';

-- 9. 게시글 좋아요
CREATE TABLE IF NOT EXISTS HM_CLUB_POST_LIKE (
    CLUB_POST_LIKE_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '모임 게시글 좋아요 PK',
    CLUB_POST_ID BIGINT UNSIGNED NOT NULL COMMENT '모임 게시글 FK',
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '회원 FK',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
    PRIMARY KEY (CLUB_POST_LIKE_ID),
    UNIQUE KEY UK_HM_CLUB_POST_LIKE_POST_MEMBER (CLUB_POST_ID, MEMBER_ID),
    KEY IX_HM_CLUB_POST_LIKE_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_CLUB_POST_LIKE_POST FOREIGN KEY (CLUB_POST_ID) REFERENCES HM_CLUB_POST (CLUB_POST_ID),
    CONSTRAINT FK_HM_CLUB_POST_LIKE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='모임 게시글 좋아요';

-- 10. 알림 및 알림 설정
CREATE TABLE IF NOT EXISTS HM_NOTIFICATION (
    NOTIFICATION_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '알림 PK',
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '수신 회원 FK',
    NOTIFICATION_TYPE VARCHAR(50) NOT NULL COMMENT '알림 유형',
    PRIORITY VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT '중요도: NORMAL, IMPORTANT',
    TITLE VARCHAR(300) NOT NULL COMMENT '알림 제목',
    CONTENT VARCHAR(2000) NOT NULL COMMENT '알림 내용',
    TARGET_TYPE VARCHAR(30) NULL COMMENT '연결 대상 유형',
    TARGET_ID BIGINT UNSIGNED NULL COMMENT '연결 대상 PK',
    READ_STATUS VARCHAR(10) NOT NULL DEFAULT 'UNREAD' COMMENT '읽음 상태: READ, UNREAD',
    READ_AT DATETIME NULL COMMENT '읽음 일시',
    ACTION_TYPE VARCHAR(30) NULL COMMENT '액션 유형: WAITING_OFFER 등',
    ACTION_STATUS VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT '액션 상태',
    ACTION_EXPIRES_AT DATETIME NULL COMMENT '액션 만료 일시',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    EXPIRES_AT DATETIME NOT NULL COMMENT '90일 보관 만료 일시',
    PRIMARY KEY (NOTIFICATION_ID),
    KEY IX_HM_NOTIFICATION_MEMBER_READ (MEMBER_ID, READ_STATUS, CREATED_AT),
    KEY IX_HM_NOTIFICATION_EXPIRES (EXPIRES_AT),
    CONSTRAINT FK_HM_NOTIFICATION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT CK_HM_NOTIFICATION_PRIORITY CHECK (PRIORITY IN ('NORMAL','IMPORTANT')),
    CONSTRAINT CK_HM_NOTIFICATION_READ CHECK (READ_STATUS IN ('READ','UNREAD')),
    CONSTRAINT CK_HM_NOTIFICATION_ACTION CHECK (ACTION_STATUS IN ('NONE','PENDING','ACCEPTED','DECLINED','EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회원 알림';

CREATE TABLE IF NOT EXISTS HM_MEMBER_NOTIFICATION_SETTING (
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '회원 PK/FK',
    COMMENT_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REPLY_YN CHAR(1) NOT NULL DEFAULT 'Y',
    LIKE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CLUB_NOTICE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    MEETING_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CLUB_ACTIVITY_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_HM_MEMBER_NOTIFICATION_SETTING_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT CK_HM_MEMBER_NOTIFICATION_SETTING_YN CHECK (
        COMMENT_YN IN ('Y','N') AND REPLY_YN IN ('Y','N') AND LIKE_YN IN ('Y','N')
        AND CLUB_NOTICE_YN IN ('Y','N') AND MEETING_YN IN ('Y','N') AND CLUB_ACTIVITY_YN IN ('Y','N')
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회원 알림 수신 설정';

CREATE TABLE IF NOT EXISTS HM_CLUB_NOTIFICATION_SETTING (
    CLUB_NOTIFICATION_SETTING_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '회원 FK',
    CLUB_ID BIGINT UNSIGNED NOT NULL COMMENT '모임 FK',
    NEW_MEETING_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '특정 모임 새 만남 알림',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CLUB_NOTIFICATION_SETTING_ID),
    UNIQUE KEY UK_HM_CLUB_NOTIFICATION_MEMBER_CLUB (MEMBER_ID, CLUB_ID),
    KEY IX_HM_CLUB_NOTIFICATION_CLUB (CLUB_ID),
    CONSTRAINT FK_HM_CLUB_NOTIFICATION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_CLUB_NOTIFICATION_CLUB FOREIGN KEY (CLUB_ID) REFERENCES HM_CLUB (CLUB_ID),
    CONSTRAINT CK_HM_CLUB_NOTIFICATION_YN CHECK (NEW_MEETING_YN IN ('Y','N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='모임별 알림 설정';

-- 11. 신고 처리·회원 제재 이력
CREATE TABLE IF NOT EXISTS HM_REPORT_ACTION_HISTORY (
    REPORT_ACTION_HISTORY_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    REPORT_ID BIGINT UNSIGNED NOT NULL COMMENT '신고 FK',
    ADMIN_MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '처리 관리자 FK',
    BEFORE_STATUS VARCHAR(20) NOT NULL,
    AFTER_STATUS VARCHAR(20) NOT NULL,
    ACTION_TYPE VARCHAR(30) NOT NULL COMMENT '신고 처리 조치',
    ACTION_REASON VARCHAR(2000) NULL,
    ADMIN_MEMO VARCHAR(2000) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REPORT_ACTION_HISTORY_ID),
    KEY IX_HM_REPORT_ACTION_REPORT (REPORT_ID, CREATED_AT),
    KEY IX_HM_REPORT_ACTION_ADMIN (ADMIN_MEMBER_ID),
    CONSTRAINT FK_HM_REPORT_ACTION_REPORT FOREIGN KEY (REPORT_ID) REFERENCES HM_REPORT (REPORT_ID),
    CONSTRAINT FK_HM_REPORT_ACTION_ADMIN FOREIGN KEY (ADMIN_MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='신고 검토 및 조치 이력';

CREATE TABLE IF NOT EXISTS HM_MEMBER_SANCTION_HISTORY (
    MEMBER_SANCTION_HISTORY_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '제재 회원 FK',
    ADMIN_MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '처리 관리자 FK',
    REPORT_ID BIGINT UNSIGNED NULL COMMENT '근거 신고 FK',
    SANCTION_TYPE VARCHAR(30) NOT NULL COMMENT 'WARNING, SUSPENSION, PERMANENT_BAN, REPORT_RESTRICTION',
    SANCTION_STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, EXPIRED, REVOKED',
    SANCTION_REASON VARCHAR(2000) NOT NULL,
    STARTS_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ENDS_AT DATETIME NULL COMMENT '정지·신고 제한 종료 일시',
    REVOKED_AT DATETIME NULL,
    REVOKED_BY BIGINT UNSIGNED NULL COMMENT '해제 관리자 FK',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MEMBER_SANCTION_HISTORY_ID),
    KEY IX_HM_MEMBER_SANCTION_MEMBER (MEMBER_ID, SANCTION_STATUS, STARTS_AT),
    KEY IX_HM_MEMBER_SANCTION_REPORT (REPORT_ID),
    CONSTRAINT FK_HM_MEMBER_SANCTION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_MEMBER_SANCTION_ADMIN FOREIGN KEY (ADMIN_MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_MEMBER_SANCTION_REPORT FOREIGN KEY (REPORT_ID) REFERENCES HM_REPORT (REPORT_ID),
    CONSTRAINT FK_HM_MEMBER_SANCTION_REVOKED FOREIGN KEY (REVOKED_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT CK_HM_MEMBER_SANCTION_TYPE CHECK (SANCTION_TYPE IN ('WARNING','SUSPENSION','PERMANENT_BAN','REPORT_RESTRICTION')),
    CONSTRAINT CK_HM_MEMBER_SANCTION_STATUS CHECK (SANCTION_STATUS IN ('ACTIVE','EXPIRED','REVOKED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회원 경고·정지·영구정지·신고 제한 이력';

-- 12. 회원 차단·로그인 이력·공개 프로필
CREATE TABLE IF NOT EXISTS HM_MEMBER_BLOCK (
    MEMBER_BLOCK_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    BLOCKER_MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '차단 회원 FK',
    BLOCKED_MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '차단 대상 회원 FK',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MEMBER_BLOCK_ID),
    UNIQUE KEY UK_HM_MEMBER_BLOCK_PAIR (BLOCKER_MEMBER_ID, BLOCKED_MEMBER_ID),
    KEY IX_HM_MEMBER_BLOCK_BLOCKED (BLOCKED_MEMBER_ID),
    CONSTRAINT FK_HM_MEMBER_BLOCK_BLOCKER FOREIGN KEY (BLOCKER_MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT FK_HM_MEMBER_BLOCK_BLOCKED FOREIGN KEY (BLOCKED_MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT CK_HM_MEMBER_BLOCK_SELF CHECK (BLOCKER_MEMBER_ID <> BLOCKED_MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회원 간 차단';

CREATE TABLE IF NOT EXISTS HM_MEMBER_LOGIN_HISTORY (
    MEMBER_LOGIN_HISTORY_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MEMBER_ID BIGINT UNSIGNED NULL COMMENT '식별된 회원 FK, 미등록 아이디 실패는 NULL',
    LOGIN_ID VARCHAR(50) NOT NULL COMMENT '시도 로그인 아이디',
    SUCCESS_YN CHAR(1) NOT NULL COMMENT '로그인 성공 여부',
    FAILURE_REASON VARCHAR(30) NULL COMMENT '내부 통합 코드, 사용자에게 상세 미노출',
    IP_ADDRESS VARCHAR(45) NULL COMMENT 'IPv4 또는 IPv6',
    USER_AGENT VARCHAR(1000) NULL COMMENT '원시 User-Agent',
    DEVICE_INFO VARCHAR(200) NULL,
    BROWSER_INFO VARCHAR(200) NULL,
    APPROX_REGION VARCHAR(200) NULL COMMENT '대략적 접속 지역',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MEMBER_LOGIN_HISTORY_ID),
    KEY IX_HM_MEMBER_LOGIN_HISTORY_MEMBER (MEMBER_ID, CREATED_AT),
    KEY IX_HM_MEMBER_LOGIN_HISTORY_LOGIN_ID (LOGIN_ID, CREATED_AT),
    CONSTRAINT FK_HM_MEMBER_LOGIN_HISTORY_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT CK_HM_MEMBER_LOGIN_HISTORY_SUCCESS CHECK (SUCCESS_YN IN ('Y','N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회원 로그인 성공·실패 이력';

CREATE TABLE IF NOT EXISTS HM_MEMBER_PROFILE (
    MEMBER_ID BIGINT UNSIGNED NOT NULL COMMENT '회원 PK/FK',
    SELF_INTRO VARCHAR(2000) NULL COMMENT '공개 자기소개',
    INTEREST_HOBBIES VARCHAR(2000) NULL COMMENT '관심 취미',
    JOINED_CLUB_PUBLIC_YN CHAR(1) NOT NULL DEFAULT 'N',
    MEETING_ACTIVITY_PUBLIC_YN CHAR(1) NOT NULL DEFAULT 'N',
    REVIEW_PUBLIC_YN CHAR(1) NOT NULL DEFAULT 'N',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_HM_MEMBER_PROFILE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HM_MEMBER (MEMBER_ID),
    CONSTRAINT CK_HM_MEMBER_PROFILE_PUBLIC_YN CHECK (
        JOINED_CLUB_PUBLIC_YN IN ('Y','N')
        AND MEETING_ACTIVITY_PUBLIC_YN IN ('Y','N')
        AND REVIEW_PUBLIC_YN IN ('Y','N')
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회원 공개 프로필 및 공개 범위';

-- 13. 서비스 설정 및 관리자 감사 정보
CREATE TABLE IF NOT EXISTS HM_SERVICE_SETTING (
    SETTING_KEY VARCHAR(100) NOT NULL COMMENT '설정 키',
    SETTING_VALUE LONGTEXT NOT NULL COMMENT '설정 값',
    SETTING_DESCRIPTION VARCHAR(1000) NULL,
    UPDATED_BY BIGINT UNSIGNED NOT NULL COMMENT 'SUPER_ADMIN 회원 FK',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SETTING_KEY),
    KEY IX_HM_SERVICE_SETTING_UPDATED_BY (UPDATED_BY),
    CONSTRAINT FK_HM_SERVICE_SETTING_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES HM_MEMBER (MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='서비스 운영 설정';

ALTER TABLE HM_ADMIN_ACTION_HISTORY
    DROP CONSTRAINT CK_HM_ADMIN_ACTION_HISTORY_TARGET_TYPE,
    DROP CONSTRAINT CK_HM_ADMIN_ACTION_HISTORY_ACTION_TYPE,
    ADD COLUMN BEFORE_VALUE LONGTEXT NULL COMMENT '변경 전 값(JSON 등, 민감정보 마스킹)' AFTER OPERATION_ID,
    ADD COLUMN AFTER_VALUE LONGTEXT NULL COMMENT '변경 후 값(JSON 등, 민감정보 마스킹)' AFTER BEFORE_VALUE,
    ADD COLUMN CLIENT_IP VARCHAR(45) NULL COMMENT '관리자 접속 IP' AFTER AFTER_VALUE,
    ADD COLUMN USER_AGENT VARCHAR(1000) NULL COMMENT '관리자 User-Agent' AFTER CLIENT_IP,
    ADD CONSTRAINT CK_HM_ADMIN_ACTION_HISTORY_TARGET_TYPE CHECK (
        TARGET_TYPE IN ('MEMBER','CLUB','MEETING','CLUB_POST','CLUB_COMMENT','BOARD_POST','BOARD_COMMENT','REPORT','SUGGESTION','CATEGORY','SERVICE_SETTING')
    ),
    ADD CONSTRAINT CK_HM_ADMIN_ACTION_HISTORY_ACTION_TYPE CHECK (
        ACTION_TYPE IN ('SUSPEND','UNSUSPEND','WARN','PERMANENT_BAN','BLOCK','UNBLOCK','DELETE','RESTORE','APPROVE','REJECT','COMPLETE','UPDATE','FORCE_CLOSE','FORCE_CANCEL','GRANT_ADMIN','REVOKE_ADMIN','UPDATE_SETTING','ADMIN_TEMP_AUTH','ADMIN_TEMP_AUTH_CANCEL','ADMIN_TEMP_AUTH_UPDATE')
    );
