-- HobbyMate 관리자 모임 카테고리 관리 기능용 비파괴 마이그레이션
-- 적용 전 CATEGORY_NAME 중복 여부와 DISPLAY_ORDER가 1 미만인 데이터를 확인한다.
-- 기존 모임의 CATEGORY_ID FK는 유지하며 카테고리를 물리 삭제하지 않는다.

SET NAMES utf8mb4;

-- 기존 0 이하 순서는 CHECK 추가 전에 유효한 양수 값으로 보정한다.
UPDATE HM_CATEGORY
SET DISPLAY_ORDER = CATEGORY_ID
WHERE DISPLAY_ORDER < 1;

ALTER TABLE HM_CATEGORY
    ADD COLUMN DESCRIPTION VARCHAR(200) NULL
        COMMENT '관리자용 카테고리 설명'
        AFTER CATEGORY_NAME,
    MODIFY DISPLAY_ORDER INT NOT NULL DEFAULT 1
        COMMENT '노출 순서, 1 이상',
    ADD COLUMN CREATED_BY BIGINT UNSIGNED NULL
        COMMENT '등록 관리자 회원 FK'
        AFTER USE_YN,
    ADD COLUMN UPDATED_BY BIGINT UNSIGNED NULL
        COMMENT '최종 수정 관리자 회원 FK'
        AFTER CREATED_BY,
    ADD UNIQUE KEY UK_HM_CATEGORY_NAME (CATEGORY_NAME),
    ADD KEY IX_HM_CATEGORY_USE_ORDER (USE_YN, DISPLAY_ORDER, CATEGORY_ID),
    ADD KEY IX_HM_CATEGORY_CREATED_BY (CREATED_BY),
    ADD KEY IX_HM_CATEGORY_UPDATED_BY (UPDATED_BY),
    ADD CONSTRAINT FK_HM_CATEGORY_CREATED_BY
        FOREIGN KEY (CREATED_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    ADD CONSTRAINT FK_HM_CATEGORY_UPDATED_BY
        FOREIGN KEY (UPDATED_BY) REFERENCES HM_MEMBER (MEMBER_ID),
    ADD CONSTRAINT CK_HM_CATEGORY_DISPLAY_ORDER
        CHECK (DISPLAY_ORDER >= 1);
